---
# tasks file for dnf_repositories

- name: Load OS specific variables
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: Pre-flight checks
  ansible.builtin.import_tasks:
    file: "asserts.yml"

- name: Manage repository file directory
  ansible.builtin.file:
    path: "{{ repositories_managed_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Include RPM signing key related tasks
  ansible.builtin.include_tasks:
    file: "rpm-keys.yml"
  when: rpm_keys | length > 0
  # failure in check mode is expected behaviour on first run. Check mode works on second run.
  # To skip this task you can add "--skip-tags rpm_key" to your ansible-playbook command.
  tags: rpm_key

- name: Clean-up repositories set as absent
  ansible.builtin.file:
    path: "{{ repositories_managed_dir }}/{{ repository.name }}.repo"
    state: absent
  loop: "{{ dnf_repositories }}"
  loop_control:
    loop_var: repository
  when: repository.state is defined and repository.state == 'absent'

- name: Manage repository configuration file(s)
  ansible.builtin.template:
    src: rpm_repository.repo.j2
    dest: "{{ repositories_managed_dir }}/{{ repository.name }}.repo"
    owner: root
    group: root
    mode: 0644
  loop: "{{ dnf_repositories }}"
  loop_control:
    loop_var: repository
  when: repository.state is not defined or repository.state != 'absent'

- name: Configure DNF package manager to managed repository directory
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: reposdir
    value: "{{ repositories_managed_dir }}"
    state: "{% if repositories_managed %}present{% else %}absent{% endif %}"
    no_extra_spaces: true
    owner: root
    group: root
    mode: 0644

- name: Place hint of disabled default repository directory
  ansible.builtin.copy:
    content: |
      Reading *.repo files from this location has been disabled.
      Repositories are managed by Ansible in {{ repositories_managed_dir }}
    dest: "{{ repositories_default_dir }}/DISABLED.README"
    owner: root
    group: root
    mode: 0644
  when: repositories_managed

- name: Remove hint in default repository directory
  ansible.builtin.file:
    path: "{{ repositories_default_dir }}/DISABLED.README"
    state: absent
  when: not repositories_managed
