---
# tasks part of DNF package manager, dealing with RPM keys
- name: Download key file to host
  ansible.builtin.get_url:
    url: "{{ item.key }}"
    dest: "{{ dnf_repositories_managed_dir }}/{{ item.key | basename }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ rpm_keys }}"
  when:
    - item.key is uri(schemes=['ftp', 'http', 'https'])
    - item.state is not defined or item.state == 'present'

- name: Copy key file to host
  ansible.builtin.copy:
    src: "{{ item.key }}"
    dest: "{{ dnf_repositories_managed_dir }}/{{ item.key | basename }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ rpm_keys }}"
  when:
    - item.key is not uri(schemes=['ftp', 'http', 'https'])
    - item.state is not defined or item.state == 'present'

- name: Ensure state of keys in RPM key database
  ansible.builtin.rpm_key:
    key: "{{ dnf_repositories_managed_dir }}/{{ item.key | basename }}"
    state: "{{ item.state | default('present') }}"
    fingerprint: "{{ item.fingerprint | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
  loop: "{{ rpm_keys }}"
